In [4]:
classeur={
    'positif':[],
    'negatif':[]
}

In [5]:
def calc(classeur,nombre):
    if nombre>0:
       
        classeur['positif'].append(nombre)
    else:
        classeur['negatif'].append(nombre)

In [9]:
calc(classeur,0)
classeur

{'positif': [569], 'negatif': [-569, -69, 0]}

# LIST COMPREHENSION

In [23]:
import time
stat=time.time()
Liste1=[4,8,12]
L=[]
for a in Liste1:
    L.append(a**2)

end=time.time()
print(L)
print(end)

[16, 64, 144]
1639566221.05223


In [28]:
import time
stat=time.time()
L=[a**2 for a in Liste1]
end=time.time()
print(end)
L

1639566384.8423061


[16, 64, 144]

In [31]:
Liste1=[4,80,12]

In [32]:
Li=[a**2 for a in Liste1 if a>20]
Li

[6400]

# FUNCTION

In [33]:
x=-5

In [35]:
abs(x)

5

In [41]:
y=3.5

In [42]:
round(y)

4

In [46]:
y=12
bin(y)

'0b1100'

In [47]:
hex(y)

'0xc'

In [48]:
oct(y)

'0o14'

In [50]:
Liste1

[4, 80, 12]

In [53]:
Liste1.extend([5,9,6,5])
Liste1

[4, 80, 12, 5, 9, 6, 5]

In [57]:
Liste1.count(5)

2

# FORMAT

In [59]:
c="you have 35 years and you live in senegal"
c

'you have 35 years and you live in senegal'

In [61]:
x=35
ville="senegal"
c="you have {} years and you live in {}".format(x,ville)
c

'you have 35 years and you live in senegal'

# TO CREATE THE FILE

In [113]:
fil=open("labo1.txt",'w')

In [114]:
fil.write('BOnjour')
fil.close()

In [115]:
fil=open("labo1.txt",'r')
fil.read()

'BOnjour'

In [119]:
with open("waly.txt",'w') as w:
    for a in range(11):
        w.write("{}".format(a**2))
        

In [120]:
fil=open("waly.txt",'r')
fil.read()

'0149162536496481100'

# NUMPY

pip install numpy

In [7]:
import numpy as np

In [34]:
list1=np.array([2,3,5])

In [35]:
list1

array([2, 3, 5])

In [36]:
list2=np.array([12,32,52])

In [37]:
list1+list2

array([14, 35, 57])

In [38]:
type(list2)

numpy.ndarray

In [39]:
A=np.array([[2,5,3],[5,6,9]])
A

array([[2, 5, 3],
       [5, 6, 9]])

In [40]:
B=np.array([[1,0,2],[2,0,1]])
B

array([[1, 0, 2],
       [2, 0, 1]])

In [41]:
A+B

array([[ 3,  5,  5],
       [ 7,  6, 10]])

In [52]:
A=np.array([[[2,5,3],[52,6,9],[5,6,9]]])
A

array([[[ 2,  5,  3],
        [52,  6,  9],
        [ 5,  6,  9]]])

In [53]:
A.ndim

3

In [55]:
pip install pandas

     |████████████████████████████████| 11.5 MB 7.4 MB/s eta 0:00:01    |███▉                            | 1.4 MB 42 kB/s eta 0:03:58
Note: you may need to restart the kernel to use updated packages.


In [17]:
import pandas as pd

In [18]:
data=pd.read_excel("/home/amadou/lab1.xlsx")

FileNotFoundError: [Errno 2] No such file or directory: '\\home\x07madou\\lab1.xlsx'